/* ------------------------------------------------------------------
   Aeris — shared client logic.
   The actual figures live in data.live.json, regenerated by
   pipeline/build_data.py from live public sources. This file only
   holds the risk-band definitions and the status classifier.
------------------------------------------------------------------ */

/* Occupancy thresholds (%) shared by every visual. */
const BANDS = {
  normal:   { max: 70,  label: "Normal" },
  elevated: { max: 85,  label: "Erhöht" },
  critical: { max: 100, label: "Kritisch" },
};

function statusFor(pct) {
  if (pct < BANDS.normal.max) return "normal";      // < 70
  if (pct <= BANDS.elevated.max) return "elevated";  // 70–85 inclusive
  return "critical";                                 // > 85
}
